### ISSUE TITLE
Aggiornamento del file publiccode alla versione 0.1 e qualche accortezza.

### ISSUE THREAD

**Issue by r3vit** [arpa-puglia/infoaria#1]
Ciao,
stiamo portando a termine la prima fase di riorganizzazione del portale di developers.italia.it
Al fine di poter essere catalogati all'interno della piattaforma come "Software a riuso" sarebbero  importanti due accortezze:

1) se repository appartenesse ad una organizzazione il sistema di crawling controllerebbe in automatico i suoi repository, evitando la necessità di dover segnalare ed indicizzare il singolo alla piattaforma. (è possibile trasformare un account personale in una organizzazione dalle [impostazioni](https://github.com/settings/organizations) dell'account github)

2) Il file publiccode.yml deve essere valido all'ultima versione stabile. In questo caso esattamente 7 giorni fa è stata rilasciata la versione stabile 0.1, con le specifiche descritte a questo link [link](https://github.com/publiccodenet/publiccode.yml/tree/master/version/0.1)

	Alcune dei campi che sono cambiati:
	- `description/eng/longDescription` deve avere dai 500 ai 10.000 caratteri
	- `tags` è una lista [ben definita](https://github.com/publiccodenet/publiccode.yml/blob/master/version/0.1/tags.md) di tags. Per tag liberi ci sono i `freeTags`
	- Sono cambiate anche le specifiche per l'estensione italiana.

Aggiungo un link alle [linee guida](http://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/index.html).

Nel caso in cui questi requisiti fossero soddisfatti il software potrà essere aggiunto al catalogo (e sarebbe il primo o il secondo ad avere un publiccode.yml valido 😄)

**Comment by libremente** [comment]
PR fatta e accettata, grazie @arpa-puglia! :+1: 

Come ci siamo detti stamani, rimangono da verificare le informazioni relative a:
- [ ] `shortDescription` e `longDescription`;
- [ ] `categories` da verificare;
- [ ] `features` da aggiornare;
- [ ] sarebbe bello popolare la chiave `usedBy` con informazioni relative agli enti che attualmente usano il software;
- [ ] se fossero disponibili degli screenshot sarebbe interessante inserirli nel repository e poi popolare la chiave `screenshot` con la relativa URL.

Al di la del publiccode, sarebbe molto utile avere un file `README` contenente più informazioni.

Grazie ancora per l'ottimo lavoro!

**Comment by libremente** [comment]
@arpa-puglia se serve una mano per chiudere questa issue rimango a disposizione. Grazie!
